version: "3"

networks:
  etcd_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_CONFIG_SUBNET}

services:
  etcd-0:
    networks:
      etcd_net:
        ipv4_address: ${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}
    image: quay.io/coreos/etcd:latest
    ports:
      - ${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}:4001:4001
      - ${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}:2380:2380
      - ${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}:2379:2379
    hostname: etcd-0
    environment:
      - GOMAXPROCS=2
    command: >-
      /usr/local/bin/etcd
      -name etcd-0
      -advertise-client-urls http://etcd-0:2379,http://etcd-0:4001
      -listen-client-urls http://${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}:2379,http://${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}:4001
      -initial-advertise-peer-urls http://etcd-0:2380
      -listen-peer-urls http://${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}:2380
      -initial-cluster-token etcd-cluster
      -initial-cluster etcd-0=http://etcd-0:2380,etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380
      -initial-cluster-state new
  etcd-1:
    networks:
      etcd_net:
        ipv4_address: ${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}
    image: quay.io/coreos/etcd:latest
    ports:
      - ${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}:4001:4001
      - ${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}:2380:2380
      - ${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}:2379:2379
    hostname: etcd-1
    environment:
      - GOMAXPROCS=2
    command: >-
      /usr/local/bin/etcd
      -name etcd-1
      -advertise-client-urls http://etcd-1:2379,http://etcd-1:4001
      -listen-client-urls http://${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}:2379,http://${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}:4001
      -initial-advertise-peer-urls http://etcd-1:2380
      -listen-peer-urls http://${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}:2380
      -initial-cluster-token etcd-cluster
      -initial-cluster etcd-0=http://etcd-0:2380,etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380
      -initial-cluster-state new
  etcd-2:
    networks:
      etcd_net:
        ipv4_address: ${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}
    image: quay.io/coreos/etcd:latest
    ports:
      - ${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}:4001:4001
      - ${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}:2380:2380
      - ${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}:2379:2379
    hostname: etcd-2
    environment:
      - GOMAXPROCS=2
    command: >-
      /usr/local/bin/etcd
      -name etcd-2
      -advertise-client-urls http://etcd-2:2379,http://etcd-2:4001
      -listen-client-urls http://${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}:2379,http://${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}:4001
      -initial-advertise-peer-urls http://etcd-2:2380
      -listen-peer-urls http://${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}:2380
      -initial-cluster-token etcd-cluster
      -initial-cluster etcd-0=http://etcd-0:2380,etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380
      -initial-cluster-state new
