version: "3"

networks:
  etcd_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_CONFIG_SUBNET}

services:
  etcd-01:
    networks:
      etcd_net:
        ipv4_address: ${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}
    image: quay.io/coreos/etcd:latest
    ports:
      - ${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}:4001:4001
      - ${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}:2380:2380
      - ${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}:2379:2379
    hostname: etcd-01
    environment:
      - GOMAXPROCS=2
    command: >-
      /usr/local/bin/etcd
      -name etcd-01
      -advertise-client-urls http://etcd-01:2379,http://etcd-01:4001
      -listen-client-urls http://${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}:2379,http://${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}:4001
      -initial-advertise-peer-urls http://etcd-01:2380
      -listen-peer-urls http://${ETCD_01_NETWORKS_ETCD_NET_ADDRESS}:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster etcd-01=http://etcd-01:2380,etcd-02=http://etcd-02:2380,etcd-03=http://etcd-03:2380
      -initial-cluster-state new
  etcd-02:
    networks:
      etcd_net:
        ipv4_address: ${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}
    image: quay.io/coreos/etcd:latest
    ports:
      - ${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}:4001:4001
      - ${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}:2380:2380
      - ${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}:2379:2379
    hostname: etcd-02
    environment:
      - GOMAXPROCS=2
    command: >-
      /usr/local/bin/etcd
      -name etcd-02
      -advertise-client-urls http://etcd-02:2379,http://etcd-02:4001
      -listen-client-urls http://${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}:2379,http://${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}:4001
      -initial-advertise-peer-urls http://etcd-02:2380
      -listen-peer-urls http://${ETCD_02_NETWORKS_ETCD_NET_ADDRESS}:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster etcd-01=http://etcd-01:2380,etcd-02=http://etcd-02:2380,etcd-03=http://etcd-03:2380
      -initial-cluster-state new
  etcd-03:
    networks:
      etcd_net:
        ipv4_address: ${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}
    image: quay.io/coreos/etcd:latest
    ports:
      - ${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}:4001:4001
      - ${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}:2380:2380
      - ${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}:2379:2379
    hostname: etcd-03
    environment:
      - GOMAXPROCS=2
    command: >-
      /usr/local/bin/etcd
      -name etcd-03
      -advertise-client-urls http://etcd-03:2379,http://etcd-03:4001
      -listen-client-urls http://${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}:2379,http://${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}:4001
      -initial-advertise-peer-urls http://etcd-03:2380
      -listen-peer-urls http://${ETCD_03_NETWORKS_ETCD_NET_ADDRESS}:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster etcd-01=http://etcd-01:2380,etcd-02=http://etcd-02:2380,etcd-03=http://etcd-03:2380
      -initial-cluster-state new
